# Generated by Django 5.0.2 on 2025-02-24 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0002_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='sent_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacts',
            name='message',
            field=models.TextField(),
        ),
    ]
