# Generated by Django 5.0.2 on 2025-04-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0004_contactmessage_delete_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
    ]
